---
- name: Update all packages on Debian/Ubuntu hosts
  hosts: localhost
#  hosts: all
  tasks:

    - name: Update all packages to latest version
      ansible.builtin.package:
        name: "*"
        state: latest
      become: true
