---
- name: Update  packages chache on Debian/Ubuntu hosts
  hosts: localhost
#  hosts: all
  tasks:
    - name: Update package cache (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"
      become: true

    - name: Ensure jq is installed
      ansible.builtin.package:
        name: jq
        state: present
      when: ansible_os_family == "Debian"
      become: true

