---
- name: Get installed packages on linux hosts
  hosts: localhost
#  hosts: all
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Display all installed packages with name and version
      ansible.builtin.debug:
        msg: "{{ item.key }}: {{ item.value[0].version }}"
      loop: "{{ ansible_facts.packages | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Write package information to JSON file
      ansible.builtin.copy:
        content: "{{ ansible_facts.packages | to_nice_json }}"
        dest: ./packages_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.json
        mode: '0644'
